config/routes.rb
Rails.application.routes.draw do
  # get 'pages/home'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  resources :categories
  resources :budgets
  resources :transactions
  resources :accounts
  # resources :users

  root "pages#home"

end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/budget.rb
class Budget < ApplicationRecord
  belongs_to :user

  validates :name, :amount, :start_date, :end_date, :recurring, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :transactions

  validates :name, presence: true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :category
  belongs_to :account

  validates :amount, :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :lockable, :timeoutable

  has_many :categories
  has_many :budgets
  has_many :transactions
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized, except: :index
  after_action :verify_policy_scoped, only: :index
  def index

    @accounts = policy_scope(Account)
    # authorize @accounts
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, unless: :devise_controller?
  before_action :configure_permitted_parameters, if: :devise_controller?


  include Pundit::Authorization

  after_action :verify_authorized, unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?



  private

  # def skip_pundit_authorization
  #   skip_authorization
  # end

  def skip_pundit?
    devise_controller? || (params[:controller] =~ /(^(rails_)?admin)|(^pages$)/) == 0
  end


  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :email, :password, :password_confirmation])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :email])
  end

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end


  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTrackerFinal</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: 'all', "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <div class="navbar-container">
      <%= render "shared/navbar" %>
    </div>
    
    <div class="content-container">
      <%= yield %>
    </div>

    <div class="flashes-container">
      <%= render "shared/flashes" %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
  <nav class="navbar navbar-expand-lg">
  <%= link_to root_path do %>
    <p class="navbar-brand" >MONETREE</p>
  <% end %>
    <div  id="navbarNav">
      <ul class="navbar-nav">
        <% if current_user %>
          <li class="nav-item">
            <%= link_to accounts_path(current_user) do %>
              <h4 class="nav-link">Accounts<span class="sr-only"></span></h4>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to transactions_path(current_user) do %>
              <h4 class="nav-link">Transactions<span class="sr-only"></span></h4>
            <%end%>
          </li>
          <li class="nav-item">
            <%= link_to categories_path(current_user) do %>
              <h4 class="nav-link">Categories<span class="sr-only"></span></h4>
            <%end%>
          </li>
          <li class="nav-item">
            <%= link_to budgets_path(current_user) do %>
              <h4 class="nav-link">Budgets<span class="sr-only"></span></h4>
            <%end%>
        <%end%>

      </ul>
    </div>
          <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "btn btn-password log-out" %>
    <img class="avatar" alt="avatar-bordered" src="https://kitt.lewagon.com/placeholder/users/sarahlafer" />
  </nav>